- hosts: single_test_node
  remote_user: ubuntu
  become: true
  tasks:
    - name: Ping check host
      ping: ~
    - name: Download node exporter configuration file
      shell: |
        wget https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
        tar xvf node_exporter-1.3.1.linux-amd64.tar.gz
        cd node_exporter-1.3.1.linux-amd64
        cp node_exporter /usr/local/bin
        cd ..
        rm -rf ./node_exporter-1.3.1.linux-amd64
        useradd --no-create-home --shell /bin/false node_exporter
        chown node_exporter:node_exporter /usr/local/bin/node_exporter
    - name: Copy run binary configuration
      copy:
        src: "./node-exporter.cfg.d/node_exporter.service"
        dest: "/etc/systemd/system/node_exporter.service"
        owner: root
        group: root
        mode: 0644
    - name: Check if there are no errors in configuration file
      command: "test -e /etc/systemd/system/node_exporter.service"
      register: run_conf_check
    - name: Keep and reload enable node exporter service
      shell: |
        systemctl daemon-reload
        systemctl enable node_exporter
        systemctl start node_exporter
        ufw allow 9100
