- hosts: load_balancer
  remote_user: ubuntu
  become: true
  roles:
    - haproxy-server

- hosts: k8s_cluster
  remote_user: ubuntu
  become: true
  roles:
    - preprocess-kubernetes


######################################################

# - hosts: kubernetes_nodes
#   remote_user: ubuntu
#   become: true
#   roles:
#     - node-exporter

- hosts: kubespray_server
  remote_user: ubuntu
  become: true
  roles:
    - kubernetes-cluster

- hosts: kube_control_plane
  remote_user: ubuntu
  become: true
  roles:
    - posprocess-kubernetes
