---
# tasks file for node-exporter
- name: Download node exporter configuration file
  become: yes
  become_user: root
  ansible.builtin.shell: |
    wget https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    tar xvf node_exporter-1.3.1.linux-amd64.tar.gz
    cd node_exporter-1.3.1.linux-amd64
    cp node_exporter /usr/local/bin
    cd ..
    rm -rf ./node_exporter-1.3.1.linux-amd64
    useradd --no-create-home --shell /bin/false node_exporter
    chown node_exporter:node_exporter /usr/local/bin/node_exporter
    ufw allow 9100
  args:
    executable: /bin/bash

- name: Copy the node-exporter systemd service file
  become: yes
  become_user: root
  template:
    src: files/node-exporter.service
    dest: /etc/systemd/system/node_exporter.service
  changed_when: true
  notify: reload_daemon

- name: Ensure the service is running
  become: true
  become_user: root
  systemd:
    name: node-exporter.service
    enabled: true
    state: started
